apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vmservice
  namespace: vmservice
  labels:
    app: vmservice
spec:
  selector:
    matchLabels:
      app: vmservice
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
