apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuna
  namespace: vmservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tuna
  template:
    metadata:
      labels:
        app: tuna
    spec:
      containers:
        - name: tuna
          image: yuccastream/tuna:latest
          command: ["tuna", "http", "vmservice:80", "--domain", "vmautoservice.ru"]
          env:
            - name: TUNA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tuna-token
                  key: token
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "50m"
