---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vmservice-tls
spec:
  secretName: vmservice-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - vmautoservice.ru
