apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vmservice

resources:
- ../../base
- ingress.yaml

images:
- name: nginx-exporter
  newName: nginx/nginx-prometheus-exporter
  newTag: 1.1.0
- name: vmservice
  newName: ghcr.io/jaennil/vmservice
  newTag: e9785e02fa12b2ab9bd993a5bc6b9c5e11bf36d8
