apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vmservice

resources:
- ../../base
- ingress.yaml

images:
- name: nginx-exporter
  newName: nginx/nginx-prometheus-exporter
  newTag: 1.1.0
- name: vmservice
  newName: ghcr.io/jaennil/vmservice
  newTag: adb27835f4d0ff6732c97976fa0f0460566f8d59
